config/routes.rb
FriendCircle::Application.routes.draw do
  resources :users, :only => [:new, :create, :show]
  resource :session, :only => [:new, :create, :destroy]
  resources :forgotten_passwords, :only => [:new, :create]
  get '/forgotten_passwords/:reset_token' => 'forgotten_passwords#edit'
  put '/forgotten_passwords/:reset_token' => 'forgotten_passwords#update', :as => :reset_password
  resources :buddy_circles
  resources :buddy_circle_memberships, :only => [:destroy]

end

app/models/buddy_circle.rb
# == Schema Information
#
# Table name: buddy_circles
#
#  id         :integer          not null, primary key
#  owner_id   :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class BuddyCircle < ActiveRecord::Base
   attr_accessible :owner_id
   validates :owner_id, :presence => true

   belongs_to(
     :owner,
     :class_name => "User",
     :primary_key => :id,
     :foreign_key => :owner_id
    )

    has_many(
      :buddy_circle_memberships,
      :inverse_of => :circle,
      :class_name => "BuddyCircleMembership",
      :foreign_key => :circle_id,
      :primary_key => :id)


    has_many :members, :through => :buddy_circle_memberships, :source => :user
end

app/models/buddy_circle_membership.rb
# == Schema Information
#
# Table name: buddy_circle_memberships
#
#  id         :integer          not null, primary key
#  user_id    :integer          not null
#  circle_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class BuddyCircleMembership < ActiveRecord::Base
  attr_accessible :circle_id, :user_id
  validates :circle, :user_id, :presence => true

  belongs_to(
    :circle,
    :inverse_of => :buddy_circle_memberships,
    :class_name => "BuddyCircle",
    :foreign_key => :circle_id,
    :primary_key => :id)

  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)      not null
#  password_digest :string(255)      not null
#  session_token   :string(255)      not null
#  reset_token     :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :password
  validates :email, :password_digest, :session_token, :presence => true
  validates :password, :length => { :minimum => 6 }, :on => :create
  before_validation :ensure_session_token
  validates :email, :uniqueness => { :message => " already in use"}

  has_one(
    :buddy_circle,
    :class_name => "BuddyCircle",
    :primary_key => :id,
    :foreign_key => :owner_id
  )

  has_many :friends, :through => :buddy_circle, :source => :members
  has_many :friendships, :through => :buddy_circle, :source => :buddy_circle_memberships

  attr_reader :password

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def self.find_by_credentials(email, pw)
    user = User.find_by_email(email)
    user && user.is_password?(pw) ? user : nil
  end

  def is_password?(pw)
    BCrypt::Password.new(self.password_digest).is_password?(pw)
  end

  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def reset_reset_token!
    self.reset_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.reset_token
  end

  private
  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery
  include SessionsHelper
end

app/controllers/buddy_circle_memberships_controller.rb
class BuddyCircleMembershipsController < ApplicationController
  def destroy
    @membership = BuddyCircleMembership.find(params[:id])
    @membership.delete
    redirect_to buddy_circles_url
  end
end

app/controllers/buddy_circles_controller.rb
class BuddyCirclesController < ApplicationController
  def new
    @users = User.all.sort {|u1, u2| u1.email <=> u2.email}
    @users.delete(current_user)
    render :new
  end

  def create
    current_user.buddy_circle.delete
    current_user.buddy_circle = BuddyCircle.new
    current_user.buddy_circle.member_ids = params[:friends].values
    redirect_to buddy_circles_url
  end

  def index
    @circle = current_user.friendships.includes(:user)
    render :index
  end
end

app/controllers/forgotten_passwords_controller.rb
class ForgottenPasswordsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user
      @reset_token = @user.reset_reset_token!
      msg = UserMailer.password_reset(@user, @reset_token)
      msg.deliver!
      flash[:errors] = ["Email sent"]
      redirect_to new_session_url
    else
      flash.now[:errors] ||= []
      flash.now[:errors] << "Email not registered"
      render :new
    end
  end

  def edit
    @user = User.find_by_reset_token(params[:reset_token])
    render :edit
  end

  def update
    @user = User.find_by_reset_token(params[:reset_token])
    @user.password = params[:password]
    if @user.save
      @user.reset_token = nil
      redirect_to new_session_url
    else
      flash.now[:errors] ||= []
      flash.now[:errors] << @user.errors.full_messages
      render :edit
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
      )

    if @user
      log_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] ||= []
      flash.now[:errors] << "Invalid Email-Password combination"
      render :new
    end
  end


  def destroy
    current_user.reset_session_token!
    session[:token] = nil
    redirect_to new_session_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      log_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] ||= []
      flash.now[:errors] << @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def password_reset
    @user = User.find_by_reset_token(params[:reset_token])
    render :password_reset
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buddy_circle_memberships_helper.rb
module BuddyCircleMembershipsHelper
end

app/helpers/buddy_circles_helper.rb
module BuddyCirclesHelper
end

app/helpers/forgotten_passwords_helper.rb
module ForgottenPasswordsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= User.find_by_session_token(session[:token])
  end

  def log_in(user)
    session[:token] = user.reset_session_token!
  end

  def logged_in?
    !!current_user
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/buddy_circles/index.html.erb
<H4>Your friend list:</H4><br>
<% @circle.each do |friendship| %>
<%= friendship.user.email %>
<%= button_to "Remove Friend", buddy_circle_membership_url(friendship), :method => :delete %>
<% end %>

app/views/buddy_circles/new.html.erb
<form action="<%= buddy_circles_url%>" method="post">
  <%@users.each_with_index do |user, index|%>
  <label for="<%= user.id %>"><%=user.email%></label>
	<input type="checkbox" name="friends[<%=index%>]" value="<%=user.id%>" id="<%= user.id %>"> <br>
  <%end%>
  <input type="submit" value="Create Buddy Circle">
</form>

app/views/forgotten_passwords/edit.html.erb
<h1>Reset Password</h1>

<p>Enter new password</p>
<form action="<%= reset_password_url %>" method="post">
  <input type="hidden" name="_method" value="put">
  <label for="password">Password:</label>
  <input type="password" name="password" id="password">
  <input type="submit" value="Submit">
</form>

app/views/forgotten_passwords/new.html.erb
<h4>Enter your email below and we will email you instructions on resetting your
  password</h4>

  <form action="<%=forgotten_passwords_url%>" method="post">
    <label for="email">Email</label>
    <input type="text" name="email" id="email">
    <input type="submit"  value="Submit">
  </form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FriendCircle</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %>
  <% end %>
<% end %>


<%if logged_in?%>
<h4 align="right">
  <%=current_user.email%>
  <%= button_to "Log Out", session_url, :method => :delete %>
</h4>
<%end%>

<body>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post">
  <label for="email">Email</label>
  <input type="text" name="user[email]" id="email">
  <br>
  <label for="password">Password</label>
  <input type="password" name="user[password]" id="password">
  <br>
  <input type="submit" value="Sign Up">
</form>

<%= link_to "Already a member? Sign in here.", new_session_url %>

app/views/users/show.html.erb
<h1>You are signed in as: <%=@user.email%></h1>
<%= link_to "Create Your Friend List", new_buddy_circle_url %>